### PR TITLE
Standardize

### PR DESCRIPTION
**Pull request by wschella**

### CODE REVIEW

**Comment by wschella** [comment]
@abeforgit could you check why the submit event on the form gets triggered on every argument field button press?

**Comment by abeforgit** [comment]
Ok will check asap, should've tested that. Arguments probably need a
rewrite.

**Comment by wschella** [comment]
@abeforgit: note i connected it to the db already, which ment quite some changes to the existing code, so could very probably be my fault.

**Comment by abeforgit** [comment]
There's some more things broken: the check whether the bot already exists with the confirmation to overwrite doesn't exist. Also every single button on the botconfig page sends the ADD_BOT action for some reason

**Comment by abeforgit** [comment]
Got it, the argument buttons were not marked as type: 'button' so they defaulted to type: 'submit'.
Gotta love silent errors.

**Pull request merged**
