### PR TITLE
Configform

### PR DESCRIPTION
**Pull request by Robbe7730**
added the configuration form (issue #133)

### CODE REVIEW

**Comment by wschella** [comment]
I did some quick review of the result, and it behaves exactly as I'd like! 😄 The logic behind it all seems to get extended already, so i'm wondering if it makes sense to use a form generator like [this](https://github.com/SteveVitali/react-form-generator), since we probably want some functionality like required fields and validation as well. 

But since all the generators I find don't quite do it like I want it, let's just use this as is it.
@Robbe7730 Do you feel like adding required fields and validation is a lot of work?

**Comment by wschella** [comment]
Damn, just found [this](https://github.com/mozilla-services/react-jsonschema-form) lib by mozilla. And this a *very* decent project it seems. Now i'm quite sure we want to use this one. @Robbe7730 if you have any questions, or wanna rant about why i didn't propose this sooner, feel free to ask/rant.

**Comment by wschella** [comment]
I will look into merging this, together with #136 and #135 in electron today.

**Comment by iasoon** [comment]
@wschella: I discussed this with @Robbe7730 today, and we think it might be better to use a hard-coded form instead of that library. While that library is quite cool, it doesn't really offer much configuration, and it's not like we need tons of huge forms. I think we'll be able to provide a prettier and better intergrated client if we drop it.

**Comment by wschella** [comment]
@iasoon, @Robbe7730: I think I agree, but we should make sure the state interactions are clean. Seems to be the hardest part. Try to get some ideas from the lib (for example a generic array-field might prove useful).

**Comment by wschella** [comment]
Maybe we should already do it more like we are gonna do it in the future. In the online flow, you'll want to select other players (not taking into account automatic matchmaking), and then create a 'Match Lobby', where the maps, max_turns, etc is selected. So now I think we should maybe have some different components: 
- Creating bots: how to start a bot, or what we enter in the list of players right now.
- Selecting bots: from your list of bots, select those that'll play against each other
- Selecting game details: the map, amount of turns, etc...

Also, maybe should brainstorm a bit about how the client should actually work.
We did a lot of thinking about the server, but rushed head first into the client.
@iasoon @Robbe7730 ?

**Comment by iasoon** [comment]
Isn't that what we discussed?

**Comment by wschella** [comment]
I don't know what you discussed with Robbe, and i don't seem to recall much discussion about the client. Maybe it's just my memory playing up.

**Pull request merged**
